# https://docs.pytest.org/en/stable/customize.html
# для того, чтобы не нужно было при запуске тестов указывать "--alluredir allure-report"
[tool.pytest.ini_options]
addopts = "--alluredir allure-report"